# **Ejercicios de pair programming Módulo 3 Sprint 1**
## **Regresión logística: Lección 5**
### **Decision Tree**

In [1]:
# Tratamiento de datos
# ------------------------------------------------------------------------------
import numpy as np
import pandas as pd

# Gráficos
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Modelado y evaluación
# ------------------------------------------------------------------------------
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score , cohen_kappa_score, roc_curve,roc_auc_score
from sklearn.model_selection import GridSearchCV

# Configuración warnings
# ------------------------------------------------------------------------------
import warnings
warnings.filterwarnings('ignore')

Hasta ahora hemos ajustado el modelo usando una Regresión Logística, pero como hemos aprendido, podemos usar el Decision Tree en este tipo de problemas. Los objetivos de este pair programming :

 - Ajustad un modelo de Decision Tree a nuestros datos.

In [2]:
df = pd.read_csv("../datos/Invistico_Airline_procesado.csv", index_col = 0)
df.head()

,age,flight_distance,departure_delay_in_minutes,gender_oe,customer_type_oe,type_of_travel_oe,class_oe,seat_comfort_oe,departure_arrival_time_convenient_oe,food_and_drink_oe,...,inflight_entertainment_oe,online_support_oe,ease_of_online_booking_oe,on_board_service_oe,leg_room_service_oe,baggage_handling_oe,checkin_service_oe,cleanliness_oe,online_boarding_oe,satisfaction
0,0.236257,0.491272,-0.386481,0,0,0,0,2,4,4,...,2,3,2,2,2,1,2,2,2,0
1,-0.359008,0.297525,-0.281414,1,0,1,1,2,3,2,...,2,5,5,3,2,3,4,3,5,0
2,-0.557430,2.030540,8.176472,0,0,0,1,4,3,3,...,4,4,2,3,3,1,4,1,4,1
3,1.889773,0.487377,-0.386481,0,0,0,1,1,4,2,...,4,4,1,1,1,0,1,1,2,0
4,-0.689712,1.161111,-0.071280,0,0,0,0,3,2,2,...,3,3,3,3,5,3,3,4,3,0

 - Calculad las métricas a nuestro nuevo modelo.

 - Comparad las métricas con el modelo hecho hasta ahora. ¿Cuál es mejor?

In [ ]:
resultados_metricas = pd.read_csv("../datos/Invistico_Airline_metricas.csv", index_col = 0)
resultados_metricas.head()