# **Ejercicios de pair programming Módulo 3 Sprint 1**
## **Regresión lineal: Lección 10**
### **Regresión lineal: Métricas**

---

In [6]:
# Tratamiento de datos
# ----------------------------
import numpy as np
import pandas as pd

# Gráficos
# ----------------------------
import matplotlib.pyplot as plt
import seaborn as sns

#  Modelado y evaluación
# ----------------------------
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Para evitar que salgan los warnings en jupyter
# ----------------------------
import warnings
warnings.filterwarnings('ignore')

plt.rcParams["figure.figsize"] = (10,8)

pd.options.display.max_columns = None

En el pair programming anterior creastéis vuestro primer modelo de machine learning usando la regresion Lineal. Es el momento, que con vuestros datos evaluéis si es bueno haciendo predicciones. Los objetivo de este pairprogramming son:

In [7]:
df_socio = pd.read_csv('../datos/datos-regresion-lineal/5.1-esperanza_vida_encoding_eli.csv', index_col=0)
df_socio.head(2)

,region,population_in_millions,population_density,urban_population_y,gdp_per_capita,health_total_expenditure,health_care_index,quantity_of_physicians,quality_of_life_index,purchasing_power_index,safety_index,pollution_index,pop_using_improved_drinking_water,life_expectancy_at_birth_total_bc
country,,,,,,,,,,,,,,
Argentina,2,-0.178879,-0.273196,1.103154,-0.439011,-1.075299,0.742566,3.0,0.131610,-0.436682,-1.655219,0.057166,0.474870,1.596496e+11
Australia,3,-0.262734,-0.283298,0.771296,1.362030,0.630170,0.837385,2.5,1.015861,1.027351,-0.217071,-1.285658,0.710275,2.611737e+11

 - Calculéis las métricas para vuestro modelo.

In [8]:
# Volvemos a hacer la regresión del pair anterior.

y = df_socio['life_expectancy_at_birth_total_bc']
x = df_socio.drop('life_expectancy_at_birth_total_bc', axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

lr = LinearRegression(n_jobs = -1)

lr.fit(x_train, y_train)

y_predict_train = lr.predict(x_train)
y_predict_test = lr.predict(x_test)

df_train = pd.DataFrame({'real' : y_train, 'predicted' : y_predict_train, 'set' : ['train']* len(y_train)})
df_test = pd.DataFrame({'real' : y_test, 'predicted' : y_predict_test, 'set' : ['test']* len(y_test)})

resultado = pd.concat([df_train, df_test], axis=0)

resultado.head()

                     real     predicted    set
country
Brazil       1.478254e+11  1.281358e+11  train
Israel       2.622094e+11  2.228582e+11  train
Belgium      2.414933e+11  2.646976e+11  train
Serbia       1.488658e+11  1.827842e+11  train
Netherlands  2.466086e+11  2.631599e+11  train

In [9]:
resultados_metricas = {'MAE': [mean_absolute_error(y_test, y_predict_test), mean_absolute_error(y_train, y_predict_train)],
                'MSE': [mean_squared_error(y_test, y_predict_test), mean_squared_error(y_train, y_predict_train)],
                'RMSE': [np.sqrt(mean_squared_error(y_test, y_predict_test)), np.sqrt(mean_squared_error(y_train, y_predict_train))],
                'R2':  [r2_score(y_test, y_predict_test), r2_score(y_train, y_predict_train)],
                 "set": ["test", "train"], 
                 "modelo": ["Regresión Lineal", "Regresión Lineal"]}

df_resultados = pd.DataFrame(resultados_metricas)

df_resultados

            MAE           MSE          RMSE        R2    set            modelo
0  2.898687e+10  1.299378e+21  3.604689e+10  0.480343   test  Regresión Lineal
1  1.871273e+10  5.210688e+20  2.282693e+10  0.870983  train  Regresión Lineal

 - Discutid los resultados de las métricas y extraed conclusiones.

>Vamos a analizar las métricas por tipo:
>
>- R2: Podemos observar que el R2 del conjunto de entrenamiento más que duplica el R2 del conjunto del test, lo que puede sugerir que el modelo sufre un problema de *overfitting*.
>
>- MAE, MSE, RMSE: Estas tres métricas tienen valores bastante bajos, casi 0, y son muy similares en los tres casos para los dos conjuntos de datos. Aún así podemos comprobar, por ejemplo, que el RMSE del test sigue siendo más del doble que el del train. 
>
>- Podemos ver en general que las métricas se relacionan de forma más o menos estable en sus diferencias.
>

 - Guardad los resultados de las métricas en un csv para usarlo más adelante.

In [10]:
df_resultados.to_csv("../datos/datos-regresion-lineal/6.1-esperanza_vida_metricas_eli.csv")